language: scala
scala:
- 2.11.7
script:
- scripts/travis-publish.sh
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
sudo: false
notifications:
  email:
  - leachbj@bouncycastle.org
env:
  global:
  - secure: relAcuFt0lfMWWvQUpG+kCL7vLiArhaHWoRbqhiqvZmIn+SxwSmczDtDAapanun4MVHVL6gygrl7kYCZqztbZJS5S+v/c0jOpVVbvXURI0QZ7MpsaykSP7jEN3gHgleicktDTsGlnHhaAsPSpiRh8MuxzFdBoNxb8AjVApWM+aZ98+XM3mYO7+/oSKYMhg+ibConmwryFw35zcA7THPN9Afzb4Gkamj8LqNMl4sfgoJk/oARbUeEX1QtlZXq9BzGPHQ2l7sD+LFz4RljhpTGGE+wtBq9gwPtMQPTkp7jg3jQxsOeqCUKOhLPSKb30ED8HaaDtzDZZ4DFQxxQwT4vpAYeN27SmS+mNJhzU7w88lufCbGPKfLSZO1BhMfzAVtZW2lFetIEiCjuu82ZKL2JKyBMHKa9rTZBqtpk73Ln7Px1NOc7NmqEa21p7K7m93VRBDeFx31C3lMPsrPI/uQO4zZSv5cjRHPgfKybszGKj1TkjWQn43j9LyIcVnHOGgR9DMzIqInOn8Psz1fMSN+qb+PnAoMHZ7YZo8MS9DiXyR2I6L7zfYKB5M+c+aiPlkkn7H6ogQYLsFjE2seCYVQyBKvHrwG9oNRUK2uUbl/4V3IqqWgTmjwHGCycvW5sRU+eTDDtRAHvhsSN2sfBIgnVD1UrovUXAqZMCRST+nt/sgQ=
  - secure: CkwsqKSKasMpHsNEgN2lPwe+OJ3zh5QX+fbRWi3xduTkeDCjRmzU0nXDySa1+O5gUr417afG8geq0t2mWsQb5Mh5bOZ+3olIUi7vz1zixiOKvlu/bLjxnnxU9+lE+HXm59JuYMf5sPYLVb31nh7B3VBnsB6TNh80dc0leOA6zRxjm41e0lwqWtGH8yI1++efsQiRXgNiWI9OuBJPm3RJqF5uJv5Oj0tD1MP83Ytqko3ylOY7zhW0R4i86XN+JgZvov8DquWvJ/HmiCVOrpnX+4Z7hOoviYtP+BR5TYUwe0SSsibFbvpe5xTOt/2fBj3stN6+dOHCCdh/MSjWefxaNaz7bsR8JKFBX5gVMdOdlEy96r0fmwWMt03gUJjhj4MZUSSGEJExeZ/oncPR/eMBGjuMwobYC08+BIDYsuAb0USwfZTrqwOazoegg2+ZhhKiHt7tXstxY2RyK6uARrFwixYi6L4FltE/wlmljA63mgZqYnnF7yONkuwLT5ZVI1BTbReKPiQxHrNIoQdf4Lmk+je/JCvEnzzUBjjXKTf9qRfqB83Ay/NRtS/SNaelKfkUOhZ3POGSN8IgQ+yfyh5SPWc11rffHIWsJnk+R/XU5jCUqNSheFFXBmzGLXX1RW49dU83k5Yi51YDs1ybWFY2KGqPJajDSwboWL6XBIAnros=
  - secure: PlrS27NtmYzgLw18l4Hxgdn7ngROiaf48k3sRI279T64pBvoXUCQo0Rtc2Zvkz6yaiownlwLsAmC9VzxUSXXvE5smHAWiFvEIEUn2LQZvnJA/1h+FkJ4ATHyNYGd8Rm2Ojlx0j+AiBOsoJXgmfc01uRS0dLu3HBF475ONk+obFU1/rTc55/ETZFEVWgcz35NspxcXNrt5kPexWHBQXwRx1P3UzuxaSsDs/nlo5xxIxvKDpc5rqRS9SVRE3EBPdtK0myB/68IokqXcD8HKoa5OIQZ/LTUo39G7C0739W0TeL7GoZndmav5MTj3VWlZmiBgtOkYPmJ3D1HlrpuvJr7pGoYCUhWJukMB1PbijkfLWlO+e+bICOLKbrpFiRzpSSldwCP6sFxaBas3Max9XUhdM56ZFJqd5RSBigFZaJe+a5+pDQO1BY7vszL3bnYx6OARp68/7liVheTLZoEia2vwSrytQe9v0cPCfIJ6fPrOyr6lL+IH3uPftx9sAIa8zgHq9Jj94G59MRMn3bR3/iYm4Gt9lew7STL50Peou38YLnPppxqYqlAzNuy09FXBNBWoJ8OTsQDLv8gzJW016b+ygtWQRMqg9qr4YdfxuUeVOhUaf0hNRDUJOAy8cd6TVwOE7NA2ZxWykcnzRis0ffpa8rAgydgiqmoS330hX/EAbw=
